### ISSUE TITLE
Colors needs to be rounded outside of export

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#11]
currently the export rounds colors.
while it works and limits the maximum materials, this could be unexpected behaviour

**Comment by demsham** [comment]
isn't 11 colors too few anyway? if this is included, it should at least be decimals=2

**Comment by demsham** [comment]
(meaning in the case of bw)

**Comment by modellstadt** [comment]
yes, solution is for example to implement in the color module a round color method

like this user can choose how to round before exporting…

**Comment by modellstadt** [comment]
two decimals can lead to an export of 100x100x100 material definitions.
this crashed all renderers…

**Comment by demsham** [comment]
ok, my bad. so we anyway cannot give the option of choosing anything over 1

**Comment by modellstadt** [comment]
current implementation seems to not limit the amount of exported colors.
(only the amount of used colors)

**Comment by worbit** [comment]
i have two alternative suggestions:
1. we don't create a separate `*.mtl` file, but as long as we only have colors anyway and not texture coordinates, we can write them directly into the vertices, like `v x.xx y.yy z.zz r g b`
1. as most of the coloring methods are one-dimensional (`min() - max()` of some property), and then just mapped to the full rainbow hue spectrum, we only have to store one u-value and one rainbow image

what do you think?

**Comment by modellstadt** [comment]
if this works with blender (please check, vertex colors are not official part of OBJ specifications and work only in some software) and cycles and eevee render,  it would be a good solution.
the other option is implemented. the only advantage of this one would be that materials can later be changed in blender, but not relevant for the exercise

**Comment by modellstadt** [comment]
mtl with colors tested in blender (cycles and eevee), meshlab and rhino.
blender and rhino works well, meshlab displays colors a bit different

**Comment by modellstadt** [comment]
if vertex colors or rainbow texture work, I would suggest implementing this optionally.
In this case I would close this issue, and open up a new one describing this.

**Comment by worbit** [comment]
yes i know, vertex colors is (unfortunately!) not official. it works with meshlab and rhino (and used to work with keyshot) but blender doesn't seem to support it... 😖
rainbow texture is what i used for the visibility analysis vr display of the "incidental space" project. i will try to find the p5 code and maybe port it to mola, but probably no time today. but if we have one well working solution, there's maybe no urgent need for 5 more
