### ISSUE TITLE
collectNewFaces: strange notation

### ISSUE THREAD

**Issue by worbit** [dbt-ethz/mola#14]
@piter123 pointed me to the following line:
`newFace=Face([edge1.vertex,v2.vertex,edge2.vertex,face.vertex])`
[subdivision.py, L25](https://github.com/dbt-ethz/mola/blob/master/subdivision.py#L25)

so a new face should be created from a list of 4 vertices. but
1. `edge1.vertex`: edge doesn't have a property vertex, but v1 and v2
1. `v2.vertex`: v2 *is* a vertex and doesn't have a property vertex
1. see number 1
1. `face.vertex`: face has a list of vertices, but no property vertex either

this method is therefore highly susceptible to not work at all...? can the author please explain?

**Comment by modellstadt** [comment]
This property is added on the fly (thx to python)

It is a very fast way to make the necessary queries in a subdivision process.
However not intuitive...

**Comment by worbit** [comment]
ok, but only because `subdivide` or `subdivideCatmull` adds these fields first? so one would not be able to call `collectNewFaces` separately?

**Comment by modellstadt** [comment]
Yes, so we can make it private!
Its shared between every quadbased subd method

**Comment by modellstadt** [comment]
Isnt it already private? It only makes sense in the context of subdivision, so it should be! Maybe one underscore missing?
Otherwise issue can be closed

**Comment by worbit** [comment]
it is as private as it gets with python (has an underscore). pietro found it because of the upcoming c# implementation...
