### ISSUE TITLE
BabylonJS still requires lots of space for display 

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#16]
Maybe we should introduce even the option to have fixed with/height ?
The current behaviour could be related to the CSS styles 100%...
but not sure and not urgent..

**Comment by demsham** [comment]
not sure what you mean by this. even after you use the canvasWidth=x canvasHeight=y arguments?

**Comment by modellstadt** [comment]
If i run the notebooks, 

each babylon canvas has precise dimensions.
However, the next cell below has a lot of distance, and I assume this distance could be related to the css body style.
but not sure.

here a notebook to test…

https://colab.research.google.com/drive/1nWnEyb4ngfNBp7owyDk-Uy5-TBuU4mEt <https://colab.research.google.com/drive/1nWnEyb4ngfNBp7owyDk-Uy5-TBuU4mEt>
