### ISSUE TITLE
Optional 100% canvaswidth

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#17]
Not sure how to implement that, but it would be also cool if standard canvas width of babylonJS would be 100% as it was before..

One easy fix would be: width and height needs to be passed as String, together with units
. for example 1024px or 100%

other option: if no parameters are given, canvaswidth will be 100%, otherwise it will be in pixel.
what do you think?

**Comment by demsham** [comment]
the standard canvas before was 1280x720, not 100%, and now it's the same.
the 100% option in the css was referring to 100% of the parent element's width, which was fixed at 1280.

We could change this to String to include percentages, but i'm not sure if this is needed, as it would create strange aspect ratios depending on the screen—also i think in our case 'width:100%' would be ok but 'height: 100%' is something we don't want.

**Comment by modellstadt** [comment]
So what would you recommend for responsive solution?
Or is it already responsive? I thought before it was…

**Comment by demsham** [comment]
before html / body were fixed at 1280x720 & renderCanvas was 100% of the parent element, so 1280x720 as well.
if we really need a responsive solution i would suggest width:100% and height:56.25vw. it fits the browser's width while keeping the aspect ratio at 16:9. it's compatible with (nearly) all browsers https://caniuse.com/#search=vw
shoud i add this?
