### ISSUE TITLE
renderer3D.beginDraw()

### ISSUE THREAD

**Issue by demsham** [dbt-ethz/mola#19]
should we change:
`def displayMesh(mesh, canvasWidth=None, canvasHeight=None, showAxis=True, showEdges=False, edgesWidth=1.0, showWireframe=False, backgroundColor=(0,0,0)):`
`def display(faces):`

to:
`def beginDraw(canvasWidth=None, canvasHeight=None, showAxis=True, backgroundColor=(0,0,0)):`
`def displayMesh(mesh, showEdges=False, edgesWidth=1.0, showWireframe=False):`
`def display(faces, showEdges=False, edgesWidth=1.0, showWireframe=False):`

(after the next 'release' in order not to break everything.)

**Comment by modellstadt** [comment]
Sounds good to me!
