### ISSUE TITLE
Renaming Modules Display

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#29]
One thing I noticed: We don’t have the renderPiplines imported in the __init__
but I think the reason was because they require several other libraries to work with..
For me it would be ok to keep them as exception, i.ex. from mola import renderP5JS.
or is there an alternative?

**Comment by modellstadt** [comment]
yes, if i remember correctly, this was the reason. otherwise blender code would not run in processing and javascript not in rhino, etc.
we can think about renaming the modules though. instead of renderBabylonJS we can just call it render3D, instead of something with P5JS we can call it render2D, because the name of the framework is not so important for the students? and then maybe just blender, rhino and processing as additional modules, because they might also do more than just render?

**Comment by modellstadt** [comment]
possible structure:
colab3D 
colab2D 
blender
rhino
processing

**Comment by modellstadt** [comment]
we can leave __init__ as it is
and users who want to render need to import colab3D module like this:
import mola.colab3D

**Comment by modellstadt** [comment]
alternative labeling (as suggested by Mathias)
render3D
render2D
blender
rhino
processing

**Comment by modellstadt** [comment]
or:
canvas3D
canvas2D

**Comment by modellstadt** [comment]
or:
graphics2D
graphics3D

**Comment by worbit** [comment]
if we call the other modules `blender`, `rhino`, `processing` etc., i.e. by the framework, then i would vote for `colab2D` and `colab3D`.

**Comment by demsham** [comment]
colab3D + colab2D is pretty clear, ok by me.

**Comment by modellstadt** [comment]
will implement it
