### ISSUE TITLE
n-gon display

### ISSUE THREAD

**Issue by worbit** [dbt-ethz/mola#31]
i changed the `colab3D` display to feature not only triangles and quads, but any n-gons, see [here](https://github.com/dbt-ethz/mola/blob/master/colab3D.py#L97). in case of more than 3 vertices it makes a triangle fan from vertex 0. should i convert the `constructDodecaehedron` method back to return pentagons? all the subdivision should be able to handle n-gons, no?

**Comment by modellstadt** [comment]
not sure of all the subdivisions.
do we have a grid-split?

catmull for example should work

**Comment by worbit** [comment]
i tested with tapered, works well.
we have a grid split, but it checks for number of vertices first:
https://github.com/dbt-ethz/mola/blob/master/subdivision.py#L138-L140
