### ISSUE TITLE
faster 3D display with lucid?

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#33]
https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/differentiable-parameterizations/texture_synth_3d.ipynb#scrollTo=7Q4qBazEWVWg

**Comment by worbit** [comment]
why is this closed again? amazing notebook :)

**Comment by modellstadt** [comment]
They use the same strategy as us: writing javascript text (but with Three.js)
https://github.com/tensorflow/lucid/blob/master/lucid/misc/io/showing.py
