### ISSUE TITLE
righthand vs. lefthand coordinate system

### ISSUE THREAD

**Issue by worbit** [dbt-ethz/mola#35]
i only noticed now that the colab3D display with BabylonJS uses a right-hand coordinate system, while most if not all CAD packages use a left-hand system: origin in bottom left, x to the right, y to the top and z pointing out of the screen (in colab3D into the screen).

is this something that could be changed easily?

**Comment by worbit** [comment]
i mixed up left and right-hand, but the issue is the same ;)

**Comment by modellstadt** [comment]
Would avoid some confusions, I think its a good idea.
but: might require redoing of some tutorials

**Comment by worbit** [comment]
maybe, but I think it is primarily a display issue. this thread seems related:
https://forum.babylonjs.com/t/solved-coordinates-with-right-hand-rule/3747/2

it looks like one can simply add `scene.useRightHandedSystem = true;`

**Comment by worbit** [comment]
done, see here: https://github.com/dbt-ethz/mola/blob/master/colab3D.py#L126

i also adjusted the initial camera position to `(0, 5, 30)` (instead of `-30` for z)

**Comment by modellstadt** [comment]
Great! Do we need to create a new release?

**Comment by worbit** [comment]
if we want to include it, then yes. another option would be to always clone the bleeding edge master during the course, and then only at the end of the semester "freeze" the state in a release with which all the semester's notebooks should work.

i did not test it yet in *all* notebooks, just the one (MeshFromScratch) i prepared for today...

**Comment by modellstadt** [comment]
I think we should do that, you are right.
I also think every tutorial should work and use the latest version, they are meant to explain the current functionalities our lib has.


While student works should use a release, to make sure code is not breaking.
