### ISSUE TITLE
Update Adjacencies vs update Topology

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#36]
Currently our code and the examples are not clear.
Original concept was:
-weld vertices welds vertices
-update adjacencies creates edges etc..

updateTopology does both.

now we have weld vertices inside update adjacencies, so we call it two times if we call updateTopology.

option a: we kill update Topology.  +more clear.  -one cannot create edges without welding vertices.
option b: we look for more clear labeling and remove weld vertices in updateadjacencies

**Comment by modellstadt** [comment]
renaming:
updateAdjancenies -> updateEdges
constructTopology ->updateTopology

**Comment by demsham** [comment]
```
def update_topology(self):
        self.weld_vertices()
        self.update_edges()
```

if you think this naming is ok i can also implement issue #38

**Comment by modellstadt** [comment]
sounds good to me

**Comment by modellstadt** [comment]
construct methods should probably call this method as well

**Comment by modellstadt** [comment]
Is this solved? @demsham
