### ISSUE TITLE
Module Structure

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#4]
Shall we 
introduce:
mesh
io
render 

as subfolders?

**Comment by worbit** [comment]
remember when we removed “mesh” from the module names to make it lighter? now add all this overhead again?
this would lead to
from mola.mesh import factory as mf

it all depends on where mola is heading. if it is to become the python equivalent of HDGeo (parallel to compas?), then yes.
if it is to be a lightweight set of little helpers for the ACDC course, then no.

opinions?

On 12 Mar 2019, at 15:09, modellstadt <notifications@github.com<mailto:notifications@github.com>> wrote:


Shall we
introduce:
mesh
io
render

as subfolders?

**Comment by modellstadt** [comment]
Dear All,

most important design goal of labels should be:
- naming should be self explanatory. you read the name, and you know what it covers
- only then i would say shortness. of course it was good the remove mesh everywhere, it also doesn’t make sense everywhere.
- we can discuss the naming strategy soon better on phone I think


functionality: i think its good if it covers the basic content of hdgeo (the lightweight version)
- so mesh, voxel(/pixel), graph, we do have this anyway now already?

I also don’t want to make those libraries anymore for each course new.. we can now use it also in the mas t2, etc…

Best,

Benjamin
