### ISSUE TITLE
class methods internal vs external

### ISSUE THREAD

**Issue by demsham** [dbt-ethz/mola#42]
option 1  - in class
`def add(self,vertex):
`
option 2  - externalized (in faceUtils.py, vecUtils.py etc)
`def vector_add(v1,v2):
`
option 3  - in class, static?
`def vector_add(v1,v2):
`
option 4?

**Comment by demsham** [comment]
> I am afraid core is growing.
> Would it make sense to separate
> Mesh, Vertex, Edge, Face and Box in separate files?
> 
> compared to now:
> 
> core
> facutils

we should either have:
```
core
faceUtils
vecUtils
meshUtils
```
or
```
core_face
core_vertex
core_edge
core_mesh...
```

the number of files is the same in both cases.
the main difference is that since the classes are codependent we would probably need to import everything into everything for option n.2

**Comment by modellstadt** [comment]
i don't understand option:
core_face
core_vertex
core_edge
core_mesh

does it mean everything is in the same .py file? this is what we have now.
my comment was more related to the fact that core file is growing. might be a bit difficult to edit.
but also ok to keep it growing.

**Comment by modellstadt** [comment]
for students , I think both is ok to understand:
v=mola.Vertex(2,3,4)
v.add(mola.Vertex(3,5,6)) 

and 
v=mola.vector_add(mola.Vertex(2,3,4),mola.Vertex(3,5,6))

**Comment by demsham** [comment]
> i don't understand option:
> core_face
> core_vertex
> core_edge
> core_mesh
> 
> does it mean everything is in the same .py file? this is what we have now.
> my comment was more related to the fact that core file is growing. might be a bit difficult to edit.
> but also ok to keep it growing.

sorry i wasn't clear, i got the comment. these are separate .py files
naming was just an example, you can skip core and have face.py, vertex.py, edge.py, mesh.py...

**Comment by modellstadt** [comment]
ok, got it

**Comment by demsham** [comment]
> for students , I think both is ok to understand:
> v=mola.Vertex(2,3,4)
> v.add(mola.Vertex(3,5,6))
> 
> and
> v=mola.vector_add(mola.Vertex(2,3,4),mola.Vertex(3,5,6))

when first learning processing, i remember finding it more intuitive to use:
`PVector v3 = PVector.add(v1, v2);` rather than `v1.add(v2)`
not sure why, maybe because it looks more like math.

**Comment by modellstadt** [comment]
Yes, a good reason to have this version.
But the question is if this should be implemented as static method or in a faceutils modules.

The other version does something different, is faster (no new instance) can be used for chaining. So we should also have this one.

**Comment by worbit** [comment]
we also have, and this is very good, the `__add__` (and likewise `__sub__`, `__mul__` etc.) methods which allow doing `v3 = v1 + v2`

in compas, the __add__ looks like this:
```python
return Vector(self.x + other[0], self.y + other[1], self.z + other[2])
```

this requires that Vector itself is iterable and has `__getitem__` implemented, like so

```python
def __getitem__(self, key):
        if isinstance(key, slice):
            return [self[i] for i in range(*key.indices(len(self)))]
        i = key % 3
        if i == 0:
            return self.x
        if i == 1:
            return self.y
        if i == 2:
            return self.z
        raise KeyError
```

but one can then also do `v3 = v1 + [1,2,3]`

compas also has `__iadd__`, `__isub__` etc. implemented, see here:
https://github.com/compas-dev/compas/blob/master/src/compas/geometry/_primitives/vector.py#L272-L322

**Comment by modellstadt** [comment]
Yes, I thought about this too. It would be definitely a nice extension!
From what I understand about the discussion above: it is mainly about making the library easier to use, and easier to navigate within the functions.
If additional ways of doing something do not contradict with this, I would propose to implement it.
The discussed vector operations would for me fall into this category.
And for performance reasons, it would also make sense.

**Comment by demsham** [comment]
i just realized that since we have a Vertex and not a Vector, v3 = v2 + v1 is problematic. what happens to the rest of the properties? edges / generation etc.
does it make sense to have an additional Vector class and a Vector pos in the Vertex or is it overly complicated?

**Comment by modellstadt** [comment]
Good question.
I would say the v3 = v2 + v1 case would not justify a restructuring.
we can do all tutorials without it. 
I would suggest we only do changes from which the course really benefits.
