### ISSUE TITLE
Laplacian Smooth

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#47]
Would be maybe good to add, as it would allow smoothing without increasing the amount of data.

**Comment by worbit** [comment]
yes, that's a great idea! with the new mesh.copy() also easy to implement. the only(?) open question is if the mesh should automatically be welded before?

**Comment by modellstadt** [comment]
Welding: perhaps a good policy would be to always assume welded meshes and make sure welded meshes are exported?
That might give us the possibility of performance improvements..

We would anyway not need a complex topological structure for fast LP smooth..

**Comment by worbit** [comment]
_not_ need? my question about welding or not was re. the mesh topology. coincident but unwelded vertices will move in different directions through smoothing and only consider the connected vertices for the new average position?

**Comment by modellstadt** [comment]
See above. We should assume vertices are welded.

**Comment by worbit** [comment]
ok, so i have a working version implemented, see here: https://github.com/dbt-ethz/mola/blob/dev/utils_mesh.py#L11
but in line 20 i have to do a bit of an ugly hack, because `weld_vertices` changes the `mesh.vertices` not being a list anymore, but a `dict_values` object:
https://github.com/dbt-ethz/mola/blob/dev/core_mesh.py#L111
it is still iterable, but not a list anymore...

**Comment by modellstadt** [comment]
Looks ok to me like this. but i would not recreate the topology at the beginning.
If the mesh is already welded, this might have negative impact on performance.

I would perhaps also implement it without the need for edges. I can add a variation.

**Comment by worbit** [comment]
agree, the update_topology() should not be necessary. i will have to update the mesh.copy() method, to return the vertices as well.

**Comment by modellstadt** [comment]
What do you think, shall we adjust the weld vertices method to create a list of vertices again?

**Comment by worbit** [comment]
i am about to do this, currently:
`self.vertices = [v for v in weldedVertices.values()]`

**Comment by worbit** [comment]
> Looks ok to me like this. but i would not recreate the topology at the beginning. If the mesh is already welded, this might have negative impact on performance. I would perhaps also implement it without the need for edges. I can add a variation.
> […](#)

the reason for updating the topology at the beginning lays in the mesh.copy() previously not correctly copying the topological attributes (edges).

a version without the need for edges sounds interesting as well!

**Comment by modellstadt** [comment]
a version without the need for edges is implemented (but in comments)
not sure if it is faster...
