### ISSUE TITLE
obj export, automatic .obj ending?

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#49]
this method could be a bit more tolerant, 
for example, automatically add .obj to filenames which do not have it yet.
could also allow folder path names treated differently

**Comment by worbit** [comment]
agree, it could try to handle whatever input it gets
what if it gets other file extensions, e.g. *.stl or *.txt? replace with *.obj? or just

```python
if filename.endswith('.obj')==False:
    filename += '.obj'
```

what if folders don't exist?

**Comment by modellstadt** [comment]
I would propose only handling missing .obj ending with an automatic fix.
Other exceptions -> error message?

**Comment by worbit** [comment]
other file extensions could also be handled, e.g. with

```python
parts = filename.split('.')
if parts[-1]!='obj':
    parts[-1] = 'obj'
    filename = '.'.join(parts)
```

but i agree to throw an error in case something even weirder is passed to the method ;)

**Comment by modellstadt** [comment]
Yes, i think if someone uses another file extension, he might expect the method to do something completely different anyway.

**Comment by modellstadt** [comment]
@worbit did you add your code into the exporter? can we close this issue?

**Comment by worbit** [comment]
implemented and tested
