### ISSUE TITLE
analysis and vec methods habe overlap

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#5]
Not sure if its needed, but could be merged into one module with all geometric calculatins

**Comment by modellstadt** [comment]
I would suggest to put all of it in vec,
resulting in one less module, and we can remove some redundancies.

**Comment by demsham** [comment]
in my understanding the difference is that 'analysis' is for face (or mesh) analysis and up until now was using the convention function(face) while 'vec' is for mathematical operations of points. one solution would be to move functions like center(vertices) or perimeter(vertices) to analysis and make this more clear, or merge them as you said.

**Comment by modellstadt** [comment]
this is also a good option, i would vote for this. moving everything related to face / list of vertices to anaylisis

**Comment by worbit** [comment]
I also agree on this. Circular imports should be avoided…
If we decided to create yet another object type, in my eyes we should then rename them… I know, we had this discussion already with the HD lib, but for me the hierarchy from general to specific would be


  *   Vector (any dimension)
     *   Point (2-3 dimensions, tied to cartesian coordinates)
        *   Vertex / Node (part of an assembly, graph or mesh, additional properties like e.g. edge list)

What’s your take on this?
Best, Mathias


On 18 Mar 2019, at 09:16, modellstadt <notifications@github.com<mailto:notifications@github.com>> wrote:


this is also a good option, i would vote for this. moving everything related to face / list of vertices to anaylisis

**Comment by modellstadt** [comment]
This sounds right.

About Vector->Point->Vertex relation:
Would this be inheritence? While i think it feels clear, a vector with arbitrary dimension might require another implementation, i. Ex. array of numbers? its probably a bit more memory heavy for the point/vertex case...for large meshes this might matter

But why not? Happy to test this!

About vertex or node: here i would say vertex, more often used! And a node in a graph might not carry any coordinate...

**Comment by worbit** [comment]
yes, i see.
so a Vertex would be the common child of a Point (geometry) and a Node (topology)...

On 18 Mar 2019, at 10:16, modellstadt <notifications@github.com<mailto:notifications@github.com>> wrote:

This sounds right.

About Vector->Point->Vertex relation:
Would this be inheritence? While i think it feels clear, a vector with arbitrary dimension might require another implementation, i. Ex. array of numbers? its probably a bit more memory heavy for the point/vertex case...for large meshes this might matter

But why not? Happy to test this!

About vertex or node: here i would say vertex, more often used! And a node in a graph might not carry any coordinate...

**Comment by modellstadt** [comment]
Yeah! In java we solve this by interfaces, but python allows multiple parents?

But in any case, we should still try to keep it as simple as possible...
