### ISSUE TITLE
__slots__ for performance improvement in vertex?

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#51]
Could be faster and less memory. anyone experience with this?
Would be possible to change it without impact on user interface

**Comment by worbit** [comment]
i don't have experience with `__slots__` but what i read sounds quite fitting for our vertices. however, this would not allow constructs like the following:
https://github.com/dbt-ethz/mola/blob/dev/utils_mesh.py#L31-L32
unless we add `vertex` and `nNbs` in the slots as well.

**Comment by worbit** [comment]
maybe we can give it a try, should be just one line to add and everything else still works? to see if there are any significant performance improvements

**Comment by modellstadt** [comment]
the point you mention about adding fields is critical. But I thought I read somewhere that its still possible.
But one would need to explicitly add a __dict__
Here is a good post explaining a lot, from someone who was working on this model.
https://stackoverflow.com/questions/472000/usage-of-slots

Especially under the section **Add '__dict__' to __slots__ to get dynamic assignment:**
Yes would be worth trying, is there an easy way to create benchmarks in python?
