### ISSUE TITLE
Merging Branch

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#52]
Shall we merge the dev branch?
Would it still be possible to address this branch with the current import statement in Colab?

If not, shall we keep it like this?

**Comment by worbit** [comment]
merging the branch would allow us to temporarily "break" things, e.g. when implementing and testing new methods, so the students don't get the errors... 

we can merge the branch without closing it. so we can continue developing it, but don't break the master code "in production". the old example notebooks with `goodOldCamelCase` will not work anymore, only with a release but i think that's fine?

**Comment by modellstadt** [comment]
I am afraid, I would do something wrong, could you do that?
Sounds like a good strategy

**Comment by worbit** [comment]
i created a new release (v0.4-alpha) and merged dev into master. i also "merged" the other branch that was trailing from last semester by adding the two constructors (rhombic dodecahedron and octahedron) to the factory.

the old notebooks from before the major restructuring and renaming still work by doing
`!git clone -b v0.4-alpha https://github.com/dbt-ethz/mola.git`

students can now skip the `-b dev` and just do
`!git clone https://github.com/dbt-ethz/mola.git`

the `dev` branch is still open and active and i suggest we keep adding features to this one and eventually merge it into master again once it's tested and running?

**Comment by demsham** [comment]
there was a bug fix commited on the master branch yesterday. 
where do we commit the updates now? master or dev?

**Comment by worbit** [comment]
changes that we know will work reliably and are needed / used by the ACDC students go into master. try-out stuff and experimental features that may temporarily break other things go into dev. once they are sufficiently tested and approved, they go into master as well. what do you think?

**Comment by worbit** [comment]
yesterday's commit was just a minor adjustment to the 2d drawing module, afaik...

**Comment by demsham** [comment]
> changes that we know will work reliably and are needed / used by the ACDC students go into master. try-out stuff and experimental features that may temporarily break other things go into dev. once they are sufficiently tested and approved, they go into master as well. what do you think?

but then how will the dev branch contain all the latest changes of the master as well..?
(maybe i still didn't get how branches work!)
in any case—i think any change may temporarily break other things, even for a few minutes, so i will be commiting to the dev first.

**Comment by worbit** [comment]
that's a good point. whenever there are changes in `master`, we also need to pull and merge them into `dev`. here is a visualization of the current branching/forking tree: https://github.com/dbt-ethz/mola/network

**Comment by demsham** [comment]
@worbit what is the way to merge dev into master without breaking anything?

**Comment by worbit** [comment]
i merged master into dev and dev into master, so both are up to date again. we can use master in the ACDC course and have all the latest additions available!
