### ISSUE TITLE
Changes we had to make to use module_rhino.py inside grasshopper

### ISSUE THREAD

**Issue by eleniv3d** [dbt-ethz/mola#57]
1. _Added imports_
from mola.core_mesh import Mesh
from mola.core_vertex import Vertex
from mola.core_face import Face

![imports](https://user-images.githubusercontent.com/43600924/76860695-bb2fb500-685b-11ea-8b27-6fd7520c1e1d.JPG)

2. _Construct Face with **a list of** vertices_
mesh.faces.append(Face([mesh.vertices[face[0]],mesh.vertices[face[1]],mesh.vertices[face[2]]]))
mesh.faces.append(Face([mesh.vertices[face[0]],mesh.vertices[face[1]],mesh.vertices[face[2]],mesh.vertices[face[3]]]))
![list_of_faces](https://user-images.githubusercontent.com/43600924/76861039-401ace80-685c-11ea-90c4-808ec4523e84.JPG)

3. _Return RhinoMesh_
mesh = rs.AddMesh(vertices,facesIndices,None,None,vertexColors)
return mesh
![return_mesh](https://user-images.githubusercontent.com/43600924/76861161-70626d00-685c-11ea-8323-83c287a6be95.JPG)

**Comment by worbit** [comment]
Thanks a lot, Eleni!
