### ISSUE TITLE
bug in obj export group

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#63]
<img width="1008" alt="Screen Shot 2020-03-24 at 8 20 09 PM" src="https://user-images.githubusercontent.com/11557248/77471198-27895600-6e12-11ea-9744-c064c8d144cb.png">

**Comment by modellstadt** [comment]
if exportGroups is turned off, export works

**Comment by modellstadt** [comment]
@worbit: Did you fix this?

**Comment by worbit** [comment]
yes, i did. only in master though, not in dev (yet)
