### ISSUE TITLE
shortest path can crash

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#7]
no solution for absolute unreachable path

**Comment by worbit** [comment]
can it not crash anymore? i think the dijkstra implementation in my colab example notebook should be robust...

On 20 Mar 2019, at 07:39, modellstadt <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #7<https://github.com/dbt-ethz/mola/issues/7>.

**Comment by modellstadt** [comment]
yes, it cannot crash anymore..
the important aspect is just, if I understand it right, that the end condition (in this -1 as precedent node) is guaranteed if a node was not reached
