### ISSUE TITLE
construct_sphere

### ISSUE THREAD

**Issue by modellstadt** [dbt-ethz/mola#72]
Would be great to have this, with separate u and v resolution.

**Comment by demsham** [comment]
https://colab.research.google.com/drive/1-7ToFUl8dE1F3CFfsJcTQNYkshLsaHO6?usp=sharing

**Comment by demsham** [comment]
added in master as
`def construct_sphere(radius=1, cx=0, cy=0, cz=0, u_res=10, v_res=10):`

**Comment by worbit** [comment]
amazing, great addition!
for more, we have methods for many primitive [shapes in COMPAS](https://github.com/compas-dev/compas/tree/master/src/compas/geometry/_shapes) as well, e.g. for the capsule: https://github.com/compas-dev/compas/blob/master/src/compas/geometry/_shapes/capsule.py#L157

**Comment by worbit** [comment]
and rhino has - in addition to UV - also the options _triangle_ and _quad_ 
<img width="895" alt="Screenshot 2020-04-07 at 09 43 54" src="https://user-images.githubusercontent.com/1062395/78643674-e6cf1980-78b4-11ea-8b31-4b1fcda46dd3.png">
this, we could easily add by starting from a primitive and subdivision, then rescale the vertices to radius
